n_cores:
    8
GTF_ref:
    /home/groups/CEDAR/anno/CellRanger/GRCh38/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
repeat_mask:
    /home/groups/precepts/enright/experiments/single_cell/GTF_files/hg38_repeatmask.gtf
sam_mem:
    50000
seurat_cluster:
    Celltype

