n_cores:
    4
GTF_ref:
    /home/groups/precepts/enright/experiments/single_cell/GTF_files/refdata-cellranger-hg19-3.0.0/genes/genes.gtf
repeat_mask:
    /home/groups/precepts/enright/experiments/single_cell/GTF_files/hg38_repeatmask.gtf
sam_mem:
    50000
seurat_cluster:
    "seurat_clusters"

